// vim: textwidth=80 ts=2 sw=2 expandtab
/**
 * @file loader.c
 */

#include "proc_parser.h"
#include "proc_structs.h"
#include "proc_gen.h"
#include "proc_syntax.h"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

void dealloc_process(process_t *p);
void dealloc_resources(resource_t *r);
void dealloc_mailboxes(void);
void dealloc_data_structures(void);

void print_jobs(char *msg, pcb_t *pcb);
void print_resources(void);
void print_mailboxes(void);
void print_instructions(char *msg, instr_t *nxt_instr);

void enqueue_job(pcb_t *pcb);
char *last_job_name = "";
int total_num_jobs = 0;
int num_ready_jobs = 0;

pcb_t *job_queue = NULL;

resource_t *first_resource = NULL;
resource_t *last_resource = NULL;

instr_t *first_instruction = NULL;
instr_t *last_instruction = NULL;

mailbox_t *first_mailbox = NULL;
mailbox_t *last_mailbox = NULL;

void init_loader(void)
{
  last_job_name = malloc(sizeof(char));
  last_job_name[0] = '\0';
}

/**
 * @brief Returns a pointer to the linked list of loaded PCBs
 *
 * Returns a pointer to the first process in the linked list
 * of loaded processes parsed by proc_parser.c.
 *
 * @return A pointer to the first process control block in the linked list.
 */
bool_t init_loader_from_files(char *filename) {
  if (parse_process_file(filename) == FALSE) printf("Error parsing %s\n", filename);
  //pcb_t *to_schedule = longterm_scheduler();
  print_jobs("Processes in the job queue", job_queue);
  print_resources();

  return (job_queue != NULL);
}

/**
 * @brief Returns a pointer to the first process in the pcb list
 *
 * Returns a pointer to the first process in the list
 * of loaded processes generated by proc_gen.c.
 *
 * @return firstPCB Pointer to the first process control block.
 */
bool_t init_loader_from_generator(void) {
  /* generate processes to initialise ready queue */
  int n = generate_procs();
  if (n <= 0) printf("Error generating procs\n");
  //pcb_t *to_schedule = longterm_scheduler();
  print_jobs("Processes in the job queue", job_queue);
  print_resources();

  return (job_queue != NULL);
}

/**
 * @brief Adds the new pcb to the list of pcbs
 *
 * Adds a newly created pcb to the list of pcbs
 *
 * @param the pcb to add
 */
void enqueue_job(pcb_t *new_pcb) {
  pcb_t *cur;

  if (job_queue == NULL) {
    job_queue = new_pcb;
  } else {
    cur = job_queue;
    while (cur->next != NULL) {
      cur = cur->next;
    }
    cur->next = new_pcb;
  }

  #ifdef DEBUG_LOADER
    print_jobs("Loaded", job_queue);
  #endif
}

/**
 * \brief Initialises and loads the processes specified in the process.list
 * file.
 *
 * This function initialises a new process control block for the process being
 * loaded from the process.list file. It initialises a number of pointers to
 * NULL as well as setting the processState to NEW.
 *
 * \param process_name The name of the new process to load
 */
bool_t load_process(char* process_name, int priority) {
  process_t *new_process = malloc(sizeof(process_t));

  pcb_t *pcb = NULL;
  if (new_process) {
    pcb = malloc(sizeof(pcb_t));
    pcb->process = new_process;
    pcb->state = NEW;
    pcb->next_instruction = NULL;
    pcb->priority = priority;
    pcb->next = NULL;

    pcb->process->name = process_name;
    pcb->process->number = ++total_num_jobs;

    enqueue_job(pcb);
  }

  if (pcb) return TRUE;
  else return FALSE;
}

void load_ready_procs(int n) {
  num_ready_jobs = n;
}

/**
 * @brief Loads the mailbox from the process.list file.
 *
 * Loads a mailbox resource and adds it to the list of mailboxes.
 *
 * @param mailbox_name The name of the mailbox to load.
 */
bool_t load_mailbox(char* mailbox_name) {
  mailbox_t *tmp_mailbox = malloc(sizeof(mailbox_t));
  int success = TRUE;
 
  if (tmp_mailbox) {
    if (first_mailbox == NULL) {
      first_mailbox = tmp_mailbox;
      first_mailbox->next = NULL;
      last_mailbox = first_mailbox;
    } else {
      last_mailbox->next = tmp_mailbox;
      last_mailbox = tmp_mailbox;
    }
    last_mailbox->name = mailbox_name;
    last_mailbox->next = NULL;
  } else {
    success = FALSE;
  }
 
 #ifdef DEBUG_LOADER
   printf("Added %s; ", mailbox_name);
   print_mailboxes();
 #endif
 
 return success;
}

/**
 * @brief Loads a resource from the process.list file.
 *
 * Loads a resource and adds it to the list of resources. The resource
 * is indicated as available and the resource name is stored.
 *
 * @param resource_name The name of the resource to load.
 */
bool_t load_resource(char *resource_name) {
  resource_t *tmp_resource = malloc(sizeof(resource_t));
  bool_t success = TRUE;
 
  if (tmp_resource) {
    if (first_resource == NULL) {
      first_resource = tmp_resource;
      last_resource = first_resource;
    } else {
      last_resource->next = tmp_resource;
      last_resource = tmp_resource;
    }
    last_resource->name = resource_name;
    last_resource->allocated = NULL;
    last_resource->next = NULL;
  } else {
    success = FALSE;
  }
#ifdef DEBUG_LOADER
  printf("Added %s; ", resource_name);
  print_resources();
#endif

  return success;

}

/**
 * @brief Loads an instruction for a process.
 *
 * The function uses the process_name to locate the process for
 * which the instruction should be loaded as well as the resource
 * on which the action is performed.
 *
 * @param process_name The name of the process for which to load the
 * instruction.
 * @param resource_name The name of the resource used in the instruction.
 * @param instruction Indicates the next request, release or message to send.
 */
bool_t load_instruction(char *process_name, instr_types_t instruction,
  char *resource_name, char *msg) {
  bool_t success = TRUE;

  instr_t *tmp_instr = malloc(sizeof(struct instr_t));
  pcb_t *pcb = NULL;

  if (tmp_instr) {
    if (strcmp(last_job_name, process_name) != 0) {
      first_instruction = tmp_instr;
      first_instruction->next = NULL;
      last_instruction = first_instruction;
    } else {
      tmp_instr->next = NULL;
      last_instruction->next = tmp_instr;
      last_instruction = tmp_instr;
    }

    last_instruction->resource_name = resource_name;
    switch (instruction) {
    case SEND_OP:
    case RECV_OP:
      last_instruction->type = instruction;
      last_instruction->msg = msg;
      break;
    default:
      last_instruction->type = instruction;
      last_instruction->msg = NULL;
      break;
    }

    pcb = job_queue;
    if (pcb != NULL) {
      do {
        if(strcmp(pcb->process->name, process_name) == 0) break;
        pcb = pcb->next;
      } while (pcb != NULL);
      pcb->next_instruction = first_instruction;
      pcb->process->first_instr = first_instruction;
    }
    last_job_name = process_name;
  } else {
    success = FALSE;
  }

  return success;
}

/**
 * @brief Remove n (n <= #items in job_queue) jobs from the job_queue
 * This is effectively the long-term scheduler or job scheduler that manages the degree of multiprogramming in the system
 * See Section 3.2.2 in Operating System Concepts by Silberschatz, Galvin, and Gagne
 *
 * @return a pointer to the removed linked list of jobs
 */
pcb_t *longterm_scheduler(void) {
  if (job_queue == NULL) return NULL;

  int i = 0;
  pcb_t *selected_jobs = job_queue;
  pcb_t *last_job_selected = job_queue;
  while ((i++ < num_ready_jobs) && (job_queue != NULL)) {
    last_job_selected = job_queue;
    job_queue = job_queue->next;
  }
  if (last_job_selected != NULL) last_job_selected->next = NULL;
  // Reset long-term scheduler load size to 1 after the initial ready processes are loaded
  if (job_queue != NULL) num_ready_jobs = 1;

#ifdef DEBUG_LOADER
  char *msg = malloc(64*sizeof(char));
  sprintf(msg, "Longterm scheduler jobs selected");
  print_jobs(msg, selected_jobs);
#endif

  return selected_jobs;
}

/**
 * @brief Returns the first pointer to the available resources.
 *
 * Returns the first pointer to the available resources.
 *
 * @return first_resource Pointer to the resource list.
 */
struct resource_t *get_resources(void) {
  return first_resource;
}

/**
 * @brief Returns the first pointer to the available mailboxes.
 *
 * Returns the first pointer to the available mailboxes.
 *
 * @return first_mailbox Pointer to the mailbox list.
 */
struct mailbox_t* get_mailboxes(void) {
  return first_mailbox;
}

/**
 * @brief Returns the number of processes created
 *
 * @return total_num_jobs: id assigned to the last process
 */
int get_total_jobs(void) {
  return total_num_jobs;
}

/**
 * @brief Returns the number of processes ready for scheduling
 *
 * @return num_ready_jobs
 */
int get_ready_jobs(void) {
  return num_ready_jobs;
}

/**
 * @brief Frees the allocated memory for the process struct.
 *
 * Frees the name stored in the structed followed by the struct.
 */
void dealloc_process(struct process_t *p) {
  if (p != NULL) {
    free(p->name);
    free(p);
  }
}

/**
 * @brief Frees the allocated memory for the instruction struct.
 *
 * Frees the instruction struct.
 */
void dealloc_instruction(struct instr_t *i) {
  if(i != NULL) {
    free(i);
  }
}

/**
 * @brief Frees the resources used in the system.
 *
 * Frees a linked list of resources
 */
void dealloc_resources(resource_t *r) {
  resource_t *resource;
  resource_t *next_resource;

  if (r != NULL) {
    resource = r;
    do {
      next_resource = resource->next;
      free(resource);
      resource = next_resource;
    } while (resource != NULL);
  }
}

/**
 * @brief Frees all the memory allocated for a linked list of PCBs.
 *
 * Iterates over the loaded process PCBs, starting from ll, freeing all the
 * allocated memory assigned to each process.
 */
void dealloc_pcbs(pcb_t *pcb) {
  pcb_t *next_pcb;
  instr_t *instruction;
  instr_t *next_instruction;

  if (pcb != NULL) {

    do {
      instruction = pcb->process->first_instr;

      while (instruction != NULL) {
        next_instruction = instruction->next;
        dealloc_instruction(instruction);
        instruction = next_instruction;
      }

      dealloc_process(pcb->process);

      next_pcb = pcb->next;
      free(pcb);
      pcb = next_pcb;
    } while(pcb != NULL);
  }
}

/**
 * @brief Frees the mailboxes used in the system.
 *
 * Free each of the mailboxes which are available and used in the system.
 */
void dealloc_mailboxes(void) {
  mailbox_t *mailbox;
  mailbox_t *next_mailbox;

  mailbox = get_mailboxes();
  if(mailbox != NULL) {
    do {
      free(mailbox->name);
      if(mailbox->msg != NULL) {
        free(mailbox->msg);
      }
      next_mailbox = mailbox->next;
      free(mailbox);
      mailbox = next_mailbox;
    } while (mailbox != NULL);
  }
}

/**
 * @brief Frees the memory for all the data structures
 *
 */
void dealloc_data_structures(void) {
  resource_t *resources;
  pcb_t *pcbs;

  /* Frees the memory for resources not assigned to processes */
  resources = get_resources();
  dealloc_resources(resources);
  pcbs = job_queue;
  dealloc_pcbs(pcbs);
  dealloc_mailboxes();
}

/**
 * @brief Frees the allocated memory for the process struct.
 */
void dealloc_last_job_name(void) {
  free(last_job_name);
}

void print_jobs(char *msg, pcb_t *pcb) {
  pcb_t *cur = pcb;
  printf("%s: ", msg);
  while (cur != NULL) {
    printf("%s (%d) ", cur->process->name, cur->priority);
    cur = cur->next;
  }
  printf("\n");
}

void print_num_ready_jobs(void) {
  printf("Number of processes to enter ready queue: %d", num_ready_jobs);
}

void print_resources(void) {
  resource_t *resource = first_resource;
  printf("Resources: ");
  while (resource != NULL) {
    printf("%s ", resource->name);
    resource = resource->next;
  }
  printf("\n");
}

void print_mailboxes(void) {
  mailbox_t *mailbox;
  mailbox = first_mailbox;
  printf("mailboxes : ");
  while (mailbox != NULL) {
    printf("%s ", mailbox->name);
    mailbox = mailbox->next;
  }
  printf("\n");
}

void print_instructions(char *msg, instr_t *nxt_instr) {
  instr_t *cur_instr = nxt_instr;
  if (nxt_instr == NULL) cur_instr = first_instruction;
  printf("%s: ", msg);
  while (cur_instr != NULL) {
    printf("%s %s\n  ", (cur_instr->type == REQ_OP)?"req":"rel", cur_instr->resource_name);
    cur_instr = cur_instr->next;
  }
  printf("\n");
}
